apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: domambia/tickening-auth
      context: auth # folder contain all this files
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts" #find all files ending with .ts
            dest: .
