apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 5
  selector: # which pod the deployment to manage
    matchLabels:
      app: posts
  template: # creating a pod
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: domambia/simple-backend:0.0.2
